### ISSUE TITLE
latest commit won't run in hass 0.88. (hassio in docker)

### ISSUE THREAD

**Issue by vandalon** [gerard33/home-assistant#6]
```
2019-02-25 22:04:25 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.media_player.braviatv_psk. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/media_player/braviatv_psk.py", line 10, in <module>
    from homeassistant.components.media_player import (
ImportError: cannot import name 'SUPPORT_TURN_ON' from 'homeassistant.components.media_player' (/usr/local/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py)
2019-02-25 22:04:25 ERROR (MainThread) [homeassistant.loader] Unable to find platform braviatv_psk
```

**Comment by gerard33** [comment]
Looking at the error code you are not using the latest version.
Please check the file in your custom_components folder and compare that with the latest version.
https://raw.githubusercontent.com/gerard33/home-assistant/master/braviatv_psk.py

Please also check if you are not using both the old and new folder names (so folder media_player and folder braviatv_psk).

**Comment by vandalon** [comment]
you are absolutely right. i forgot that I've copied the file instead of hardlinking :)

Sorry!
